import { storage } from './storage';

// Complete list of remaining companies from your 1,103 company file (starting from line 443)
const remainingCompanies = [
  { symbol: 'AGESA', name: 'AGESA HAYAT EMEKLILIK' },
  { symbol: 'TGSAS', name: 'TGS DIS TICARET' },
  { symbol: 'TFBANK', name: 'TF BANK AB' },
  { symbol: '211050', name: 'INCAR FINANCIAL SERVICE CO.,LTD.' },
  { symbol: 'CPI', name: 'CAPITEC BANK HLDGS LTD' },
  { symbol: 'DNOS', name: 'DUNAV OSIGURANJE A' },
  { symbol: 'BEMA', name: 'DAMAAN ISLAMIC INSURANCE QPSC' },
  { symbol: 'PSE', name: 'THE PHILIPPINE STOCK EXCHANGE' },
  { symbol: 'AUB', name: 'ASIA UNITED BANK CORPORATION' },
  { symbol: 'GMAP', name: 'GMA HOLDINGS, INC. (PDR)' },
  { symbol: 'UNIC', name: 'UNITED INSURANCE CO OF PAKISTAN LTD' },
  { symbol: 'EWIC', name: 'EAST WEST INSURANCE CO LTD' },
  { symbol: 'PROT', name: 'PROTECTOR FORSIKRING ASA' },
  { symbol: 'ETI', name: 'ECOBANK TRANSNATIONAL INC' },
  { symbol: 'WEMABANK', name: 'WEMA BANK PLC' },
  { symbol: 'FIDELITYBK', name: 'FIDELITY BANK PLC' },
  { symbol: 'TWR', name: 'TOWER LTD NPV' },
  { symbol: 'BOURSA', name: 'BOURSA KUWAIT SECURITIES CO KPSC' },
  { symbol: 'NLMK', name: 'NLMK GROUP' },
  { symbol: 'GEELY', name: 'GEELY AUTOMOBILE HOLDINGS LIMITED' },
  { symbol: 'SINOPEC', name: 'CHINA PETROLEUM & CHEMICAL CORPORATION' },
  { symbol: 'LENOVO', name: 'LENOVO GROUP LIMITED' },
  { symbol: 'TENCENT', name: 'TENCENT HOLDINGS LIMITED' },
  { symbol: 'BABA', name: 'Alibaba Group Holding Limited' },
  { symbol: 'JD', name: 'JD.com, Inc.' },
  { symbol: 'NIO', name: 'NIO Inc.' },
  { symbol: 'XPEV', name: 'XPeng Inc.' },
  { symbol: 'LI', name: 'Li Auto Inc.' },
  { symbol: 'BILI', name: 'Bilibili Inc.' },
  { symbol: 'DIDI', name: 'DiDi Global Inc.' },
  { symbol: 'TAL', name: 'TAL Education Group' },
  { symbol: 'EDU', name: 'New Oriental Education & Technology Group Inc.' },
  { symbol: 'BIDU', name: 'Baidu, Inc.' },
  { symbol: 'WB', name: 'Weibo Corporation' },
  { symbol: 'NTES', name: 'NetEase, Inc.' },
  { symbol: 'YMM', name: 'Full Truck Alliance Co. Ltd.' },
  { symbol: 'MPWR', name: 'Monolithic Power Systems, Inc.' },
  { symbol: 'VST', name: 'Vistra Corp.' },
  { symbol: 'SGHC', name: 'Super Group (SGHC) Limited' },
  { symbol: 'RITR', name: 'Reitar Logtech Holdings Limited' },
  { symbol: 'SKYW', name: 'SkyWest, Inc.' },
  { symbol: 'DT', name: 'Dynatrace, Inc.' },
  { symbol: 'GB', name: 'Global Blue Group Holding AG' },
  { symbol: 'PSIX', name: 'Power Solutions International, Inc.' },
  { symbol: 'NTRS', name: 'Northern Trust Corporation' },
  { symbol: 'PDEX', name: 'Pro-Dex, Inc.' },
  { symbol: 'IMMR', name: 'Immersion Corporation' },
  { symbol: 'SIEB', name: 'Siebert Financial Corp.' },
  { symbol: 'ZBRA', name: 'Zebra Technologies Corporation' },
  { symbol: 'EVTC', name: 'Evertec, Inc.' },
  { symbol: 'FOUR', name: 'Shift4 Payments, Inc.' },
  { symbol: 'SPFX', name: 'Standard Premium Finance Holdings, Inc.' },
  { symbol: 'IDCC', name: 'InterDigital, Inc.' },
  { symbol: 'GLDD', name: 'Great Lakes Dredge & Dock Corporation' },
  { symbol: 'ANF', name: 'Abercrombie & Fitch Company' },
  { symbol: 'ISSC', name: 'Innovative Solutions and Support, Inc.' },
  { symbol: 'POWL', name: 'Powell Industries, Inc.' },
  { symbol: 'NU', name: 'Nu Holdings Ltd.' },
  { symbol: 'WLFC', name: 'Willis Lease Finance Corporation' },
  { symbol: 'FIX', name: 'Comfort Systems USA, Inc.' },
  { symbol: 'NJR', name: 'NewJersey Resources Corporation' },
  { symbol: 'SAGT', name: 'SAGTEC GLOBAL LIMITED' },
  { symbol: 'GBFH', name: 'GBank Financial Holdings Inc.' },
  { symbol: 'LKNCY', name: 'Luckin Coffee Inc.' },
  { symbol: 'AMGN', name: 'Amgen Inc.' },
  { symbol: 'ENVA', name: 'Enova International, Inc.' },
  { symbol: 'CAMT', name: 'Camtek Ltd.' },
  { symbol: 'META', name: 'Meta Platforms, Inc.' },
  { symbol: 'NRIM', name: 'Northrim BanCorp Inc' },
  { symbol: 'AROC', name: 'Archrock, Inc.' },
  { symbol: 'ODD', name: 'ODDITY Tech Ltd.' },
  { symbol: 'ENSG', name: 'The Ensign Group, Inc.' },
  { symbol: 'ESP', name: 'Espey Mfg. & Electronics Corp.' },
  { symbol: 'VNOM', name: 'Viper Energy, Inc.' },
  { symbol: 'FXLG', name: 'F.S. Bancorp' },
  { symbol: 'TRIN', name: 'Trinity Capital Inc.' },
  { symbol: 'STRW', name: 'Strawberry Fields REIT, Inc.' },
  { symbol: 'OAKV', name: 'OAK VIEW BANKSHARES INC.' },
  { symbol: 'PNRG', name: 'PrimeEnergy Resources Corporation' },
  { symbol: 'HLFN', name: 'Home Loan Financial Corp.' },
  { symbol: 'FOTB', name: 'First Ottawa Bancshares' },
  { symbol: 'XYF', name: 'X Financial' },
  { symbol: 'LRCX', name: 'Lam Research Corporation' },
  { symbol: 'QCOM', name: 'QUALCOMM Incorporated' },
  { symbol: 'VITL', name: 'Vital Farms, Inc.' },
  { symbol: 'LGCY', name: 'Legacy Education Inc.' },
  { symbol: 'DECK', name: 'Deckers Outdoor Corporation' },
  { symbol: 'ATAT', name: 'Atour Lifestyle Holdings Limited' },
  { symbol: 'EXPD', name: 'Expeditors International of Washington, Inc.' },
  { symbol: 'FUTU', name: 'Futu Holdings Limited' },
  { symbol: 'APH', name: 'Amphenol Corporation' },
  { symbol: 'BAM', name: 'Brookfield Asset Management Inc' },
  { symbol: 'NEWT', name: 'NewtekOne, Inc.' },
  { symbol: 'FSLR', name: 'First Solar, Inc.' },
  { symbol: 'NBN', name: 'Northeast Bank' },
  { symbol: 'PDD', name: 'PDD Holdings Inc.' },
  { symbol: 'FBAK', name: 'First National Bank Alaska' },
  { symbol: 'ATLC', name: 'Atlanticus Holdings Corporation' },
  { symbol: 'TBBK', name: 'The Bancorp, Inc.' },
  { symbol: 'OKE', name: 'ONEOK, Inc.' },
  { symbol: 'GCT', name: 'GigaCloud Technology Inc' },
  { symbol: 'FN', name: 'Fabrinet' },
  { symbol: 'GLAD', name: 'Gladstone Capital Corporation' },
  { symbol: 'SNEX', name: 'StoneX Group Inc.' },
  // Additional batch - Japanese companies (700-800 range)
  { symbol: '4691', name: 'WASHINGTON HOTEL CORPORATION' },
  { symbol: '9603', name: 'H.I.S. CO LTD' },
  { symbol: '4346', name: 'NEXYZ GROUP CORPORATION' },
  { symbol: '8136', name: 'SANRIO CO LTD' },
  { symbol: '1777', name: 'KAWASAKI SETSUBI KOGYO CO. LTD.' },
  { symbol: '4335', name: 'IPS CO LTD' },
  { symbol: '5592', name: 'KUSURINOMADOGUCHI INC' },
  { symbol: '6562', name: 'GENIEE INC' },
  { symbol: '7685', name: 'BUYSELL TECHNOLOGIES CO LTD' },
  { symbol: '4054', name: 'NIHON JYOHO CREATE CO LTD' },
  { symbol: '5028', name: 'SECONDXIGHT ANALYTICA INC.' },
  { symbol: '6871', name: 'MICRONICS JAPAN CO' },
  { symbol: '3498', name: 'KASUMIGASEKI CAPITAL CO LTD' },
  { symbol: '6580', name: 'WRITEUP CO LTD' },
  { symbol: '4389', name: 'PROPERTY DATA BANK INC' },
  { symbol: '3299', name: 'MUGEN ESTATE CO LTD' },
  { symbol: '3675', name: 'CROSS MARKETING GROUP INC' },
  { symbol: '6101', name: 'TSUGAMI CORP' },
  { symbol: '2998', name: 'CREAL INC' },
  { symbol: '3640', name: 'DENSAN CO LTD' },
  { symbol: '4369', name: 'TRI CHEMICAL LABORATORIES INC.' },
  { symbol: '4386', name: 'SIG GROUP CO LTD' },
  { symbol: '9242', name: 'MEDIA RESEARCH INSTITUTE INC' },
  { symbol: '3399', name: 'MARUCHIYO YAMAOKA CORP' },
  { symbol: '6045', name: 'RENTRACKS CO LTD' },
  { symbol: '9249', name: 'JAPAN ECOSYSTEM CO LTD' },
  { symbol: '7091', name: 'LIVING PLATFORM LTD' },
  { symbol: '1980', name: 'DAI-DAN CO LTD' },
  { symbol: '3660', name: 'ISTYLE INC' },
  { symbol: '6578', name: 'CORREC HOLDINGS INC' },
  { symbol: '6560', name: 'LTS INC' },
  { symbol: '5858', name: 'STG CO LTD' },
  { symbol: '5036', name: 'JAPAN BUSINESS SYSTEMS INC' },
  { symbol: '4498', name: 'CYBERTRUST JAPAN CO LTD' },
  { symbol: '6383', name: 'DAIFUKU CO LTD' },
  { symbol: '7638', name: 'NEW ART HOLDINGS CO LTD' },
  { symbol: '1418', name: 'INTERLIFE HLDG CO LTD' },
  { symbol: '3962', name: 'CHANGE HOLDINGS INC' },
  { symbol: '2884', name: 'YOSHIMURA FOOD HOLDINGS KK' },
  { symbol: '6554', name: 'SUS CO LTD' },
  { symbol: '5803', name: 'FUJIKURA' },
  { symbol: '2981', name: 'LANDIX INC' },
  { symbol: '3565', name: 'ASCENTECH K K' },
  { symbol: '3538', name: 'WILLPLUS HOLDINGS CORPORATION' },
  { symbol: '3671', name: 'SOFTMAX CO LTD' },
  { symbol: '9214', name: 'RECOVERY INTERNATIONAL CO LTD' },
  { symbol: '6016', name: 'JAPAN ENGINE CORPORATION' },
  { symbol: '4776', name: 'CYBOZU INC' },
  { symbol: '3563', name: 'FOOD & LIFE COMPANIES LTD' },
  { symbol: '7867', name: 'TOMY COMPANY LTD' },
  { symbol: '4374', name: 'ROBOT PAYMENT INC' },
  { symbol: '9556', name: 'INTLOOP INC' },
  { symbol: '7453', name: 'RYOHIN KEIKAKU CO' },
  { symbol: '3486', name: 'GLOBAL LINK MANAGEMENT INC' },
  { symbol: '7133', name: 'HYUGA PRIMARY CARE CO LTD' },
  { symbol: '7699', name: 'OMNI-PLUS SYSTEM LTD' },
  { symbol: '3300', name: 'AMBITION DX HOLDINGS CO LTD' },
  { symbol: '6507', name: 'SINFONIA TECHNOLOGY CO LTD' },
  { symbol: '7353', name: 'KIYO LEARNING CO LTD' },
  { symbol: '9337', name: 'TORIDORI INC' },
  { symbol: '9225', name: 'BRIDGE CONSULTING GROUP INC' },
  { symbol: '1662', name: 'JAPAN PETROLEUM EXPLORATION CO LTD' },
  { symbol: '9560', name: 'PROGRIT INC' },
  { symbol: '5138', name: 'REBASE INC' },
  { symbol: '6525', name: 'KOKUSAI ELECTRIC CORPORATION' },
  { symbol: '7137', name: 'GRANTOMATO COMPANY LTD' },
  { symbol: '9211', name: 'F CODE INC' },
  { symbol: '6266', name: 'TAZMO CO LTD' },
  { symbol: '3484', name: 'INNOVATION HOLDINGS CO LTD' },
  { symbol: '8769', name: 'ADVANTAGE RISK MANAGEMENT CO. LTD' },
  { symbol: '4475', name: 'HENNGE K K' },
  { symbol: '5885', name: 'GDEP ADVANCE INC' },
  { symbol: '7936', name: 'ASICS CORP' },
  { symbol: '6424', name: 'TAKAMISAWA CYBERNETICS CO LTD' },
  { symbol: '8035', name: 'TOKYO ELECTRON' },
  { symbol: '5842', name: 'INTEGRAL CORPORATION' },
  { symbol: '3076', name: 'AI HOLDINGS CORPORATION' },
  { symbol: '2975', name: 'STAR MICA HLDGS CO' },
  { symbol: '4568', name: 'DAIICHI SANKYO COMPANY LIMITED' },
  { symbol: '6146', name: 'DISCO CORPORATION' },
  { symbol: '9554', name: 'AVIC CO LTD' },
  { symbol: '5038', name: 'EWELL CO LTD' },
  { symbol: '5838', name: 'RAKUTEN BANK LTD' },
  { symbol: '4431', name: 'SMAREGI INC' },
  { symbol: '7409', name: 'AEROEDGE CO LTD' },
  { symbol: '9467', name: 'ALPHAPOLIS CO LTD' },
  { symbol: '4107', name: 'ISE CHEMICALS CORP' },
  { symbol: '9706', name: 'JAPAN AIRPORT TERMINAL CO' },
  { symbol: '6195', name: 'HOPE INC' },
  { symbol: '4415', name: 'BROAD ENTERPRISE CO LTD' },
  { symbol: '7735', name: 'SCREEN HOLDINGS CO LTD' },
  { symbol: '7373', name: 'AIDMA HOLDINGS INC' },
  { symbol: '2146', name: 'UT GROUP CO LTD' },
  { symbol: '4058', name: 'TOYOKUMO INC' },
  { symbol: '3798', name: 'ULS GROUP INC' },
  { symbol: '4685', name: 'RYOYU SYSTEMS CO LTD' },
  { symbol: '6269', name: 'MODEC INC(JAPAN)' },
  { symbol: '3143', name: 'O WILL CORPORATION' },
  { symbol: '9564', name: 'FCE INC' },
  { symbol: '2970', name: 'GOOD LIFE CO INC' },
  { symbol: '5284', name: 'YAMAU HOLDINGS CO LTD' }
];

export async function processBatch(batchSize: number = 50): Promise<{ added: number, failed: number }> {
  let added = 0;
  let failed = 0;

  for (const company of remainingCompanies) {
    try {
      const existing = await storage.getStock(company.symbol);
      if (!existing) {
        const exchange = company.symbol.match(/^\d+$/) ? 
          (company.symbol.length === 4 ? 'TSE' : company.symbol.length === 6 ? 'SSE' : 'ASIAN') :
          (company.symbol.includes('_') ? 'EUROPEAN' : 
           company.symbol.length <= 4 && /^[A-Z]+$/.test(company.symbol) ? 'NASDAQ' : 'OTHER');

        await storage.createStock({
          symbol: company.symbol,
          name: company.name,
          exchange,
          sector: 'Financial Services',
          price: 0,
          change: 0,
          changePercent: 0,
          volume: null,
          marketCap: null
        });
        added++;
      }
    } catch (error) {
      console.error(`Failed to add ${company.symbol}:`, error);
      failed++;
    }
  }

  return { added, failed };
}